#Practica supervivencia Titanic - ML

In [3]:
import pandas as pd
import numpy as np

In [13]:
#Cargar datos
df = pd.read_csv('titanic.csv')

In [6]:
#Exploracion de datos
df.head(5)

Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2         1       3                              Miss. Laina Heikkinen   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4         0       3                            Mr. William Henry Allen   

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0    male  22.0                        1                        0   7.2500  
1  female  38.0                        1                        0  71.2833  
2  female  26.0                        0                        0   7.9250  
3  female  35.0                        1                        0  53.1000  
4    male  35.0                        0                        0   8.0500

In [8]:
df.describe()

Survived      Pclass         Age  Siblings/Spouses Aboard  \
count  887.000000  887.000000  887.000000               887.000000   
mean     0.385569    2.305524   29.471443                 0.525366   
std      0.487004    0.836662   14.121908                 1.104669   
min      0.000000    1.000000    0.420000                 0.000000   
25%      0.000000    2.000000   20.250000                 0.000000   
50%      0.000000    3.000000   28.000000                 0.000000   
75%      1.000000    3.000000   38.000000                 1.000000   
max      1.000000    3.000000   80.000000                 8.000000   

       Parents/Children Aboard       Fare  
count               887.000000  887.00000  
mean                  0.383315   32.30542  
std                   0.807466   49.78204  
min                   0.000000    0.00000  
25%                   0.000000    7.92500  
50%                   0.000000   14.45420  
75%                   0.000000   31.13750  
max                   6.000000  512.32920

##Preprocesmaiento

In [14]:
def f(x):
  if x == 'male':
    return 1
  else:
    return 0

In [15]:
df['Sex'] = df['Sex'].apply(f)
df.head(10)

Survived  Pclass                                               Name  Sex  \
0         0       3                             Mr. Owen Harris Braund    1   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...    0   
2         1       3                              Miss. Laina Heikkinen    0   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle    0   
4         0       3                            Mr. William Henry Allen    1   
5         0       3                                    Mr. James Moran    1   
6         0       1                             Mr. Timothy J McCarthy    1   
7         0       3                      Master. Gosta Leonard Palsson    1   
8         1       3   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson    0   
9         1       2                 Mrs. Nicholas (Adele Achem) Nasser    0   

    Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0  22.0                        1                        0   7.2500  
1  38.0                        1                        0  71.2833  
2  26.0                        0                        0   7.9250  
3  35.0                        1                        0  53.1000  
4  35.0                        0                        0   8.0500  
5  27.0                        0                        0   8.4583  
6  54.0                        0                        0  51.8625  
7   2.0                        3                        1  21.0750  
8  27.0                        0                        2  11.1333  
9  14.0                        1                        0  30.0708

In [16]:
df = df[df['Fare'] <200]

In [18]:
df = df.reset_index(drop=True)

In [19]:
df.describe()

Survived      Pclass         Sex         Age  \
count  867.000000  867.000000  867.000000  867.000000   
mean     0.378316    2.335640    0.651672   29.395813   
std      0.485247    0.822131    0.476715   14.141065   
min      0.000000    1.000000    0.000000    0.420000   
25%      0.000000    2.000000    0.000000   20.000000   
50%      0.000000    3.000000    1.000000   28.000000   
75%      1.000000    3.000000    1.000000   38.000000   
max      1.000000    3.000000    1.000000   80.000000   

       Siblings/Spouses Aboard  Parents/Children Aboard        Fare  
count               867.000000               867.000000  867.000000  
mean                  0.520185                 0.367935   26.607540  
std                   1.103426                 0.793761   29.395841  
min                   0.000000                 0.000000    0.000000  
25%                   0.000000                 0.000000    7.895800  
50%                   0.000000                 0.000000   14.000000  
75%                   1.000000                 0.000000   30.000000  
max                   8.000000                 6.000000  164.866700

In [20]:
X = df[['Sex', 'Age', 'Fare']].values
y = df['Survived'].values

In [21]:
X

array([[ 1.    , 22.    ,  7.25  ],
       [ 0.    , 38.    , 71.2833],
       [ 0.    , 26.    ,  7.925 ],
       ...,
       [ 0.    ,  7.    , 23.45  ],
       [ 1.    , 26.    , 30.    ],
       [ 1.    , 32.    ,  7.75  ]])

In [22]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,

##Train and test

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [24]:
X_train

array([[ 1.    , 18.    , 11.5   ],
       [ 1.    , 17.    ,  8.6625],
       [ 1.    , 23.    ,  7.8958],
       ...,
       [ 1.    , 34.    , 21.    ],
       [ 1.    , 42.    ,  7.8958],
       [ 1.    , 29.    ,  7.775 ]])

In [26]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [28]:
print(model.predict([[0, 5, 100]]))

[1]


In [29]:
print(model.predict_proba([[0, 5, 100]]))

[[0.0739308 0.9260692]]


In [30]:
print(model.predict([[1, 40, 20]]))

[0]


In [31]:
print(model.predict_proba([[1, 40, 20]]))

[[0.85308688 0.14691312]]


In [32]:
from sklearn.metrics import accuracy_score
y_predict = model.predict(X_test)
print(accuracy_score(y_predict, y_test))

0.7701149425287356


In [33]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_predict, y_test))

[[127  35]
 [ 25  74]]


##Save model

In [ ]:
import pickle
pickle.dump(model, open('model.sav', 'wb'))
modelo_importado = pickle.load(open['model.sav', 'rb'])